image = gemblerz/ros-isaac-realsense2

build-amd64:
	docker build -t $(image):humble-amd64 -f Dockerfile.amd64 .

build-jp512:
	docker build -t $(image):humble-jp512 -f Dockerfile.jp512 .

build-jp61:
	docker build -t $(image):humble-jp61 -f Dockerfile.jp61 .