FROM ros:humble

RUN apt-get update \
  && apt-get install -y \
  ros-humble-librealsense2* \
  wget \
  curl \
  nano \
  dumb-init \
  python3-pip

RUN apt-get install -y \
  ros-humble-realsense2-* \
  ros-humble-rviz2

RUN pip3 install -U pip \
  && pip install rclpy

# NOTE: Running ROS with root prohibits non-root users
#     to subscribe topics
RUN useradd -m -u 1000 ros
USER ros

ENTRYPOINT ["/ros_entrypoint.sh"]