image = gemblerz/ros-isaac-realsense2

build-amd64:
	docker build -t $(image):2.1.0-humble-amd64 -f Dockerfile.amd64 .

build-amd64-cuda:
	docker build -t $(image):2.1.0-humble-amd64-cuda -f Dockerfile.amd64_cuda .

build-jp512:
	docker build -t $(image):2.1.0-humble-jp512 -f Dockerfile.jp512 .

build-jp61:
	docker build -t $(image):2.1.0-humble-jp61 -f Dockerfile.jp61 .