apiVersion: v1
kind: Pod
metadata:
  name: vslam-debug
spec:
  nodeSelector:
    kubernetes.io/hostname: theone
  # hostNetwork: true
  containers:
  - name: vslam-debug
    image: gemblerz/ros-isaac-realsense2:humble-amd64
    command: ["/bin/bash"]
    args:
    - -c
    - "while true; do sleep 1; done"
    resources:
      limits:
        cpu: 4000m
        memory: 1Gi
      requests:
        cpu: 2000m
        memory: 500Mi
  #   volumeMounts:
  #   - mountPath: /dev
  #     name: host-dev
  # volumes:
  # - name: host-dev
  #   hostPath:
  #     path: /dev
  #     type: Directory
