apiVersion: v1
kind: Pod
metadata:
  name: vslam-nx512-debug
spec:
  nodeSelector:
    kubernetes.io/hostname: nx512
  hostNetwork: true
  containers:
  - name: vslam-nx512-debug
    image: gemblerz/ros-isaac-realsense2:2.1.0-humble-jp512
    command: ["/bin/bash"]
    args:
    - -c
    - "while true; do sleep 1; done"
    resources:
      limits:
        cpu: 4
        memory: 3Gi
      requests:
        cpu: 2
        memory: 1Gi
  #   volumeMounts:
  #   - mountPath: /dev
  #     name: host-dev
  # volumes:
  # - name: host-dev
  #   hostPath:
  #     path: /dev
  #     type: Directory
