apiVersion: v1
kind: Pod
metadata:
  name: vslam-rtx20x0
spec:
  nodeSelector:
    kubernetes.io/hostname: rtx2080
  # hostNetwork: true
  containers:
  - name: vslam-rtx20x0
    image: gemblerz/ros-isaac-realsense2:3.2.0-humble-amd64-cuda
    command: ["/bin/bash"]
    args:
    - -c
    - "while true; do sleep 1; done"
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 4000m
        memory: 3Gi
      requests:
        cpu: 2000m
        memory: 1Gi
    volumeMounts:
    - mountPath: /dev
      name: host-dev
  volumes:
  - name: host-dev
    hostPath:
      path: /dev
      type: Directory
